//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGisPostOfficeByIndex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostOffices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostOffices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DGisPostOfficeByIndex.PostOffices", typeof(PostOffices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101000	МОСКВА
        ///102001	МОСКВА-КАЗАНСКИЙ ВОКЗАЛ ПЖДП-1
        ///102101	МОСКВА-ЯРОСЛАВСКИЙ ВОКЗАЛ ПЖДП-1
        ///102151	МОСКВА-ПАВЕЛЕЦКИЙ ВОКЗАЛ ПЖДП-1
        ///102241	МОСКВА-БЕЛОРУССКИЙ ВОКЗАЛ ОПП-1
        ///102301	МОСКВА-ВНУКОВО АОПП-1
        ///102321	МОСКВА-ДОМОДЕДОВО АОПП-1
        ///103070	МОСКВА 70
        ///103132	МОСКВА 132
        ///103265	МОСКВА 265
        ///103274	МОСКВА 274
        ///103426	МОСКВА 426
        ///105005	МОСКВА 5
        ///105037	МОСКВА 37
        ///105043	МОСКВА 43
        ///105062	МОСКВА 62
        ///105064	МОСКВА 64
        ///105066	МОСКВА 66
        ///105077	МОСКВА 77
        ///105082	МОСКВА 82
        ///105094	МОСКВА 94
        ///105118	МОСКВА 118
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OPSs {
            get {
                return ResourceManager.GetString("OPSs", resourceCulture);
            }
        }
    }
}
